### ISSUE TITLE
Radius Client isn't working PwCrypt not defined in the Client Class.

### ISSUE THREAD

**Issue by mauriciogalindo** [wichert/pyrad#39]
Hi I am trying to run the client following the documentation.
It looks like the PwCrypt function is not defined in the pyrad.client.Client.
I am receiving the errors below, the code is:
Please advice if things changed on how to create a password using PwCrypt.
# create request
req = srv.CreateAuthPacket(code=pyrad.packet.AccessRequest,
                           User_Name="wichert", NAS_Identifier="localhost")
req["User-Password"] = req.PwCrypt("password")

/scripts$ ./clientradius.py 
Traceback (most recent call last):
  File "./clientradius.py", line 16, in <module>
    req["User-Password"] = req.PwCrypt("password")
  File "build/bdist.linux-i686/egg/pyrad/packet.py", line 189, in __setitem__
  File "build/bdist.linux-i686/egg/pyrad/packet.py", line 126, in _EncodeKeyValues
KeyError: 'User-Password'

**Comment by GIC-de** [comment]
It seems that `User-Password` is not defined in your dictionary.
