### ISSUE TITLE
Error message when run default example with python3

### ISSUE THREAD

**Issue by elcolie** [wichert/pyrad#55]
`https://github.com/wichert/pyrad/blob/master/example/server.py`
`https://github.com/wichert/pyrad/blob/master/example/coa.py`

From the `server.py` example 
I ran `server.py` with `python 3.6.1`
And another terminal `coa.py`

I got error
```python
Traceback (most recent call last):
  File "radius_client.py", line 35, in <module>
    main()
  File "radius_client.py", line 31, in main
    test_call()
  File "radius_client.py", line 14, in test_call
    User_Name="wichert", NAS_Identifier="localhost")
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/client.py", line 91, in CreateAuthPacket
    return host.Host.CreateAuthPacket(self, secret=self.secret, **args)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/host.py", line 56, in CreateAuthPacket
    return packet.AuthPacket(dict=self.dict, **args)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/packet.py", line 417, in __init__
    Packet.__init__(self, code, id, secret, authenticator, **attributes)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/packet.py", line 101, in __init__
    self.AddAttribute(key, value)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/packet.py", line 182, in AddAttribute
    (key, value) = self._EncodeKeyValues(key, [value])
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/pyrad/packet.py", line 137, in _EncodeKeyValues
    attr = self.dict.attributes[key]
KeyError: 'User-Name'
```

What does it means?
I am new to RADIUS, but not python

**Comment by elcolie** [comment]
NO. I was wrong. It is not related to python version
I have to place `dictionary` file in the folder as `server.py`
`dictionary` file is in the `example` directory.
My bad 😞
