### ISSUE TITLE
pyrad + python3.6

### ISSUE THREAD

**Issue by velopokatun** [wichert/pyrad#73]
Good afternoon. I used your wonderful library in python 2.7.It's time to move to 3.6 and asyncio and ran into this problem.
```

import pyrad.packet
from pyrad.dictionary import Dictionary
from pyrad.client import Client

srv = Client(
    server='localhost',
    secret=b'test',
    dict=Dictionary('/opt//dictionary')
)

req = srv.CreateAuthPacket(
    code=pyrad.packet.AccessRequest,
    User_Name='xxxxx',
)
req["User-Password"] = req.PwCrypt('yyyyy')
req['NAS-Identifier'] = 'node'
req['NAS-IP-Address'] = '0.0.0.0'

reply = srv.SendPacket(req)

'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyrad/client.py", line 173, in SendPacket
    return self._SendPacket(pkt, self.authport)
  File "/usr/local/lib/python3.6/dist-packages/pyrad/client.py", line 137, in _SendPacket
    self._socket.sendto(pkt.RequestPacket(), (self.server, port))
socket.gaierror: [Errno -2] Name or service not known
```

'''
Tell me please what this means, since the conclusion about anything does not tell me

**Comment by rbricheno** [comment]
It looks like the computer where you are running python can't resolve localhost.

I expect if you run this snippet you receive the same error:

```
import socket

print(socket.gethostbyname("localhost"))
```

Troubleshoot that before looking at pyrad. E.g. is localhost in your hosts file?

**Comment by velopokatun** [comment]
~$ python2.7
>>> import socket
>>> print(socket.gethostbyname("localhost"))
127.0.0.1

~$ python3.6
>>> import socket
>>> print(socket.gethostbyname("localhost"))
127.0.0.1

~$ nslookup localhost
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   localhost
Address: 127.0.0.1
`

**Comment by rbricheno** [comment]
Thank you, that's quite interesting. The only way I could replicate your problem was by breaking my ability to resolve localhost. I'd like to try and find a minimal case that still breaks for you. Does this break, or does it work?

```
import socket

my_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
my_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
my_socket.sendto(b'a', ("localhost", 1812))
```

That should be very close to what pyrad is doing (and works for me with no error).

Also, could you comment about what platform you are using please? E.g. windows, mac, linux distribution / version?

**Comment by velopokatun** [comment]
Sorry for the late response. The project slowed down a bit and the problem moved to the second row. The platform used Ubuntu 64 16.04 LTS

**Comment by velopokatun** [comment]
I still replace one feature that I'm sorry, did not specify. The problem arises if the address is specified in IPV6. When IPV4 everything is working fine

**Comment by GIC-de** [comment]
Please try with latest version from master which should support IPv6 as well.
